[package]
name = "myna"
version = "0.1.0"
authors = ["yuki-js <20838151+yuki-js@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
myna = "0.3.0"
wasm-bindgen = "0.2"

[profile.release]
lto = true